server:
  image: nginx:latest
  hostname: 'pokedex.com'
  volumes:
    - './settings/pokedex.conf:/etc/nginx/conf.d/default.conf'
  links:
    - 'app:app.com'
  volumes_from:
    - 'app'
  ports:
    - '3000:80'

app:
  build: .
  volumes:
    - '.:/app'


